# Generated by Django 4.0.4 on 2022-05-12 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('background', models.ImageField(upload_to='img/banners/', verbose_name='Background')),
            ],
            options={
                'db_table': 'apresentation',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='#a74242', max_length=10, verbose_name='Main Color')),
                ('strong', models.CharField(default='#661515', max_length=10, verbose_name='Strong Color')),
                ('neutral', models.CharField(default='#cccccc', max_length=10, verbose_name='Neutral Color')),
                ('lighter', models.CharField(default='#f8cfcf', max_length=10, verbose_name='Lighter Color')),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='[Nome do Blog]', max_length=100, verbose_name='Nome do Blog')),
                ('status', models.CharField(default='[Status do Blog]', max_length=100, verbose_name='Status do Blog')),
                ('owner', models.CharField(default='[Dono do Blog]', max_length=100, verbose_name='Dono do Blog')),
                ('year', models.IntegerField(default='0000', verbose_name='Publicação')),
                ('logo', models.ImageField(null=True, upload_to='img/logos/', verbose_name='Logo do Blog')),
            ],
            options={
                'db_table': 'configs',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('file', models.FileField(upload_to='pdf/', verbose_name='File')),
                ('banner', models.ImageField(upload_to='img/books/', verbose_name='Banner')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
            ],
            options={
                'db_table': 'sobre',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('banner', models.ImageField(upload_to='img/posts/', verbose_name='Banner')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.categorias')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
