# Generated by Django 4.0.4 on 2022-05-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apresentacao',
            options={'verbose_name': 'Apresentação do Site.', 'verbose_name_plural': 'Apresentações do Site.'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria do Site.', 'verbose_name_plural': 'Categorias do Site.'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Cor do Site.', 'verbose_name_plural': 'Cores do Site.'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Config do Site.', 'verbose_name_plural': 'Configs do Site.'},
        ),
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Informação do Site.', 'verbose_name_plural': 'Informações do Site.'},
        ),
    ]
