# Generated by Django 4.0.4 on 2022-05-14 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_apresentacao_options_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pages.categorias'),
        ),
    ]
